In [1]:
print("hello")

hello


In [3]:
from micrograd.engine import Value 
from micrograd.nn import MLP, Neuron, Layer

In [97]:
xs = [
  [2.0, 3.0, -1.0],
  [3.0, -1.0, 0.5],
  [0.5, 1.0, 1.0],
  [1.0, 1.0, -1.0],
]
ys = [1.0, -1.0, -1.0, 1.0] # desired targets

In [98]:
m = MLP(3, [4, 4, 1])

In [99]:
for i in range(1000): 

    # forward pass
    ypreds = [m(x) for x in xs]

    # compute loss 
    loss = sum((y - ypred) ** 2 for y, ypred in zip(ys, ypreds))

    # logging 
    print(f"loss: {loss}, step: {i}")

    # zero grad 
    m.zero_grad()
    # for p in m.parameters(): 
    #     p.grad = 0.0 
    
    loss.backward() 

    for p in m.parameters(): 
        p.data += (-0.01) * p.grad
    

loss: Value(data=12.06236326379937), step: 0
loss: Value(data=2.185952597212902), step: 1
loss: Value(data=1.8441373114829953), step: 2
loss: Value(data=1.8136789720968465), step: 3
loss: Value(data=1.783528375127351), step: 4
loss: Value(data=1.7535897238188134), step: 5
loss: Value(data=1.723851790018664), step: 6
loss: Value(data=1.6943094721569216), step: 7
loss: Value(data=1.6649600592935765), step: 8
loss: Value(data=1.635802244188837), step: 9
loss: Value(data=1.6068358118532382), step: 10
loss: Value(data=1.5780615059473644), step: 11
loss: Value(data=1.5494809447150177), step: 12
loss: Value(data=1.5210965527291305), step: 13
loss: Value(data=1.49291149918554), step: 14
loss: Value(data=1.464929639929502), step: 15
loss: Value(data=1.4371554621705842), step: 16
loss: Value(data=1.409594031366112), step: 17
loss: Value(data=1.3822509399306675), step: 18
loss: Value(data=1.3551322575022962), step: 19
loss: Value(data=1.3282444825345303), step: 20
loss: Value(data=1.3015944950088

In [100]:
ypreds = [m(x) for x in xs]

In [101]:
print(ypreds)

[Value(data=1.0000000231194113), Value(data=-0.9999999967712592), Value(data=-0.9999998932035996), Value(data=0.9999999598699643)]


In [35]:
import torch 
import torch.nn as nn

In [40]:
xs = torch.tensor([
  [2.0, 3.0, -1.0],
  [3.0, -1.0, 0.5],
  [0.5, 1.0, 1.0],
  [1.0, 1.0, -1.0],
])

In [41]:
xs.shape

torch.Size([4, 3])

In [42]:
ys = torch.tensor([1.0, -1.0, -1.0, 1.0])

In [43]:
ys.shape

torch.Size([4])

In [45]:
m = nn.Sequential(
    nn.Linear(3, 4), 
    nn.ReLU(), 
    nn.Linear(4, 4), 
    nn.ReLU(), 
    nn.Linear(4, 1)
)

In [46]:
ypreds = m(xs)

In [47]:
ypreds

tensor([[-0.2486],
        [-0.8717],
        [-0.2627],
        [-0.2545]], grad_fn=<AddmmBackward0>)

In [48]:
ypreds.shape

torch.Size([4, 1])

In [ ]:
# loss = (ypreds - ys).pow(2).sum()  # this is wrong

In [50]:
# print(loss)

tensor(19.8219, grad_fn=<SumBackward0>)


In [70]:
ys = ys.view(4, 1) # subtract same size tensors 

In [71]:
ys.shape

torch.Size([4, 1])

In [72]:
loss = (ypreds - ys).pow(2).sum() 

In [73]:
loss

tensor(3.6926, grad_fn=<SumBackward0>)

In [54]:
# example 

e1 = torch.tensor([1.0, 2.0, 3.0])
e2 = torch.tensor([[1.0], [2.0], [3.0]])

In [55]:
e1.shape 

torch.Size([3])

In [56]:
e2.shape

torch.Size([3, 1])

In [60]:
loss = (e2 - e1)

In [61]:
loss

tensor([[ 0., -1., -2.],
        [ 1.,  0., -1.],
        [ 2.,  1.,  0.]])

In [62]:
loss.shape

torch.Size([3, 3])

In [66]:
e1 = e1.view(3, 1)

In [67]:
loss = (e2 - e1)

In [68]:
loss.shape

torch.Size([3, 1])

In [69]:
loss

tensor([[0.],
        [0.],
        [0.]])

In [74]:
m.zero_grad() 

In [75]:
loss.backward()

In [76]:
for p in m.parameters(): 
    p.data += (-0.01) * p.grad 

In [83]:
m[0].weight.grad

tensor([[-0.0607,  0.1409, -0.0756],
        [-0.1750,  0.0583, -0.0292],
        [-0.1962, -0.0384, -0.1143],
        [-0.3237, -0.4856,  0.1619]])

In [84]:
m[0].weight

Parameter containing:
tensor([[ 0.4308, -0.1389,  0.2997],
        [ 0.5001, -0.3945,  0.1360],
        [ 0.1269, -0.3017,  0.3785],
        [-0.3830,  0.3777, -0.3171]], requires_grad=True)

In [85]:
ypreds = m(xs) 
loss = (ypreds - ys).pow(2).sum() 
m.zero_grad() 
loss.backward() 
for p in m.parameters(): 
    p.data += (-0.01) * p.grad 

In [86]:
m[0].weight.grad

tensor([[-0.0857,  0.1421, -0.0796],
        [-0.2054,  0.0685, -0.0342],
        [-0.2239, -0.0336, -0.1223],
        [-0.3135, -0.4703,  0.1568]])

In [88]:
m[0].weight

Parameter containing:
tensor([[ 0.4317, -0.1403,  0.3005],
        [ 0.5022, -0.3952,  0.1364],
        [ 0.1292, -0.3013,  0.3797],
        [-0.3799,  0.3824, -0.3187]], requires_grad=True)

In [89]:
loss

tensor(3.5781, grad_fn=<SumBackward0>)

In [ ]:
for i in range(1000): 
    # forward pass 
    ypreds = m(xs) 

    # compute loss 
    loss = (ypreds - ys).pow(2).sum() 

    # logging 
    print(f"loss: {loss}, step: {i}")


    # zero grad 
    m.zero_grad() 
    # alternative 
    # with torch.no_grad(): 
    #     for p in m.parameters(): 
    #         p.grad = None 

    # backward pass 
    loss.backward() 

    # weight update 
    with torch.no_grad(): 
        for p in m.parameters():
            p.data += (-0.01) * p.grad

loss: 3.4776628017425537, step: 0
loss: 3.3887577056884766, step: 1
loss: 3.309285879135132, step: 2
loss: 3.238877773284912, step: 3
loss: 3.1777901649475098, step: 4
loss: 3.122081756591797, step: 5
loss: 3.0716583728790283, step: 6
loss: 3.025139331817627, step: 7
loss: 2.9823009967803955, step: 8
loss: 2.9429049491882324, step: 9
loss: 2.906643867492676, step: 10
loss: 2.8732423782348633, step: 11
loss: 2.8432648181915283, step: 12
loss: 2.815622091293335, step: 13
loss: 2.789823055267334, step: 14
loss: 2.765934705734253, step: 15
loss: 2.743767023086548, step: 16
loss: 2.7205066680908203, step: 17
loss: 2.6567604541778564, step: 18
loss: 2.5936920642852783, step: 19
loss: 2.5305728912353516, step: 20
loss: 2.4702541828155518, step: 21
loss: 2.408539295196533, step: 22
loss: 2.347595691680908, step: 23
loss: 2.288390874862671, step: 24
loss: 2.2277889251708984, step: 25
loss: 2.1680727005004883, step: 26
loss: 2.109498977661133, step: 27
loss: 2.049623966217041, step: 28
loss: 2.0

In [91]:
ypreds = m(xs)

In [92]:
ypreds

tensor([[ 1.0000],
        [-1.0000],
        [-1.0000],
        [ 1.0000]], grad_fn=<AddmmBackward0>)

In [93]:
m.parameters()

<generator object Module.parameters at 0x11dad0740>

In [96]:
sum(p.numel() for p in m.parameters())

41